namespace GhostsAreRealButTheirIntelligenceIsArtificial.Core.Objects
{
    public class Grid
    {
        public Fixture Aa { get; set; }
        public Fixture Ab { get; set; }
        public Fixture Ac { get; set; }
        public Fixture Ad { get; set; }
        public Fixture Ae { get; set; }
        public Fixture Af { get; set; }
        public Fixture Ag { get; set; }
        public Fixture Ah { get; set; }
        public Fixture Ai { get; set; }
        public Fixture Aj { get; set; }
        public Fixture Ak { get; set; }
        public Fixture Al { get; set; }
        public Fixture Am { get; set; }
        public Fixture An { get; set; }
        public Fixture Ao { get; set; }
        public Fixture Ap { get; set; }
        public Fixture Aq { get; set; }
        public Fixture Ar { get; set; }
        public Fixture As { get; set; }
        public Fixture At { get; set; }
        public Fixture Au { get; set; }
        public Fixture Av { get; set; }
        public Fixture Aw { get; set; }
        public Fixture Ax { get; set; }
        public Fixture Ay { get; set; }
        public Fixture Az { get; set; }
        public Fixture Ba { get; set; }
        public Fixture Bb { get; set; }
        public Fixture Bc { get; set; }
        public Fixture Bd { get; set; }
        public Fixture Be { get; set; }
        public Fixture Bf { get; set; }
        public Fixture Bg { get; set; }
        public Fixture Bh { get; set; }
        public Fixture Bi { get; set; }
        public Fixture Bj { get; set; }
        public Fixture Bk { get; set; }
        public Fixture Bl { get; set; }
        public Fixture Bm { get; set; }
        public Fixture Bn { get; set; }
        public Fixture Bo { get; set; }
        public Fixture Bp { get; set; }
        public Fixture Bq { get; set; }
        public Fixture Br { get; set; }
        public Fixture Bs { get; set; }
        public Fixture Bt { get; set; }
        public Fixture Bu { get; set; }
        public Fixture Bv { get; set; }
        public Fixture Bw { get; set; }
        public Fixture Bx { get; set; }
        public Fixture By { get; set; }
        public Fixture Bz { get; set; }
        public Fixture Ca { get; set; }
        public Fixture Cb { get; set; }
        public Fixture Cc { get; set; }
        public Fixture Cd { get; set; }
        public Fixture Ce { get; set; }
        public Fixture Cf { get; set; }
        public Fixture Cg { get; set; }
        public Fixture Ch { get; set; }
        public Fixture Ci { get; set; }
        public Fixture Cj { get; set; }
        public Fixture Ck { get; set; }
        public Fixture Cl { get; set; }
        public Fixture Cm { get; set; }
        public Fixture Cn { get; set; }
        public Fixture Co { get; set; }
        public Fixture Cp { get; set; }
        public Fixture Cq { get; set; }
        public Fixture Cr { get; set; }
        public Fixture Cs { get; set; }
        public Fixture Ct { get; set; }
        public Fixture Cu { get; set; }
        public Fixture Cv { get; set; }
        public Fixture Cw { get; set; }
        public Fixture Cx { get; set; }
        public Fixture Cy { get; set; }
        public Fixture Cz { get; set; }
        public Fixture Da { get; set; }
        public Fixture Db { get; set; }
        public Fixture Dc { get; set; }
        public Fixture Dd { get; set; }
        public Fixture De { get; set; }
        public Fixture Df { get; set; }
        public Fixture Dg { get; set; }
        public Fixture Dh { get; set; }
        public Fixture Di { get; set; }
        public Fixture Dj { get; set; }
        public Fixture Dk { get; set; }
        public Fixture Dl { get; set; }
        public Fixture Dm { get; set; }
        public Fixture Dn { get; set; }
        public Fixture Do { get; set; }
        public Fixture Dp { get; set; }
        public Fixture Dq { get; set; }
        public Fixture Dr { get; set; }
        public Fixture Ds { get; set; }
        public Fixture Dt { get; set; }
        public Fixture Du { get; set; }
        public Fixture Dv { get; set; }
        public Fixture Dw { get; set; }
        public Fixture Dx { get; set; }
        public Fixture Dy { get; set; }
        public Fixture Dz { get; set; }
        public Fixture Ea { get; set; }
        public Fixture Eb { get; set; }
        public Fixture Ec { get; set; }
        public Fixture Ed { get; set; }
        public Fixture Ee { get; set; }
        public Fixture Ef { get; set; }
        public Fixture Eg { get; set; }
        public Fixture Eh { get; set; }
        public Fixture Ei { get; set; }
        public Fixture Ej { get; set; }
        public Fixture Ek { get; set; }
        public Fixture El { get; set; }
        public Fixture Em { get; set; }
        public Fixture En { get; set; }
        public Fixture Eo { get; set; }
        public Fixture Ep { get; set; }
        public Fixture Eq { get; set; }
        public Fixture Er { get; set; }
        public Fixture Es { get; set; }
        public Fixture Et { get; set; }
        public Fixture Eu { get; set; }
        public Fixture Ev { get; set; }
        public Fixture Ew { get; set; }
        public Fixture Ex { get; set; }
        public Fixture Ey { get; set; }
        public Fixture Ez { get; set; }
        public Fixture Fa { get; set; }
        public Fixture Fb { get; set; }
        public Fixture Fc { get; set; }
        public Fixture Fd { get; set; }
        public Fixture Fe { get; set; }
        public Fixture Ff { get; set; }
        public Fixture Fg { get; set; }
        public Fixture Fh { get; set; }
        public Fixture Fi { get; set; }
        public Fixture Fj { get; set; }
        public Fixture Fk { get; set; }
        public Fixture Fl { get; set; }
        public Fixture Fm { get; set; }
        public Fixture Fn { get; set; }
        public Fixture Fo { get; set; }
        public Fixture Fp { get; set; }
        public Fixture Fq { get; set; }
        public Fixture Fr { get; set; }
        public Fixture Fs { get; set; }
        public Fixture Ft { get; set; }
        public Fixture Fu { get; set; }
        public Fixture Fv { get; set; }
        public Fixture Fw { get; set; }
        public Fixture Fx { get; set; }
        public Fixture Fy { get; set; }
        public Fixture Fz { get; set; }
        public Fixture Ga { get; set; }
        public Fixture Gb { get; set; }
        public Fixture Gc { get; set; }
        public Fixture Gd { get; set; }
        public Fixture Ge { get; set; }
        public Fixture Gf { get; set; }
        public Fixture Gg { get; set; }
        public Fixture Gh { get; set; }
        public Fixture Gi { get; set; }
        public Fixture Gj { get; set; }
        public Fixture Gk { get; set; }
        public Fixture Gl { get; set; }
        public Fixture Gm { get; set; }
        public Fixture Gn { get; set; }
        public Fixture Go { get; set; }
        public Fixture Gp { get; set; }
        public Fixture Gq { get; set; }
        public Fixture Gr { get; set; }
        public Fixture Gs { get; set; }
        public Fixture Gt { get; set; }
        public Fixture Gu { get; set; }
        public Fixture Gv { get; set; }
        public Fixture Gw { get; set; }
        public Fixture Gx { get; set; }
        public Fixture Gy { get; set; }
        public Fixture Gz { get; set; }
        public Fixture Ha { get; set; }
        public Fixture Hb { get; set; }
        public Fixture Hc { get; set; }
        public Fixture Hd { get; set; }
        public Fixture He { get; set; }
        public Fixture Hf { get; set; }
        public Fixture Hg { get; set; }
        public Fixture Hh { get; set; }
        public Fixture Hi { get; set; }
        public Fixture Hj { get; set; }
        public Fixture Hk { get; set; }
        public Fixture Hl { get; set; }
        public Fixture Hm { get; set; }
        public Fixture Hn { get; set; }
        public Fixture Ho { get; set; }
        public Fixture Hp { get; set; }
        public Fixture Hq { get; set; }
        public Fixture Hr { get; set; }
        public Fixture Hs { get; set; }
        public Fixture Ht { get; set; }
        public Fixture Hu { get; set; }
        public Fixture Hv { get; set; }
        public Fixture Hw { get; set; }
        public Fixture Hx { get; set; }
        public Fixture Hy { get; set; }
        public Fixture Hz { get; set; }
        public Fixture Ia { get; set; }
        public Fixture Ib { get; set; }
        public Fixture Ic { get; set; }
        public Fixture Id { get; set; }
        public Fixture Ie { get; set; }
        public Fixture If { get; set; }
        public Fixture Ig { get; set; }
        public Fixture Ih { get; set; }
        public Fixture Ii { get; set; }
        public Fixture Ij { get; set; }
        public Fixture Ik { get; set; }
        public Fixture Il { get; set; }
        public Fixture Im { get; set; }
        public Fixture In { get; set; }
        public Fixture Io { get; set; }
        public Fixture Ip { get; set; }
        public Fixture Iq { get; set; }
        public Fixture Ir { get; set; }
        public Fixture Is { get; set; }
        public Fixture It { get; set; }
        public Fixture Iu { get; set; }
        public Fixture Iv { get; set; }
        public Fixture Iw { get; set; }
        public Fixture Ix { get; set; }
        public Fixture Iy { get; set; }
        public Fixture Iz { get; set; }
        public Fixture Ja { get; set; }
        public Fixture Jb { get; set; }
        public Fixture Jc { get; set; }
        public Fixture Jd { get; set; }
        public Fixture Je { get; set; }
        public Fixture Jf { get; set; }
        public Fixture Jg { get; set; }
        public Fixture Jh { get; set; }
        public Fixture Ji { get; set; }
        public Fixture Jj { get; set; }
        public Fixture Jk { get; set; }
        public Fixture Jl { get; set; }
        public Fixture Jm { get; set; }
        public Fixture Jn { get; set; }
        public Fixture Jo { get; set; }
        public Fixture Jp { get; set; }
        public Fixture Jq { get; set; }
        public Fixture Jr { get; set; }
        public Fixture Js { get; set; }
        public Fixture Jt { get; set; }
        public Fixture Ju { get; set; }
        public Fixture Jv { get; set; }
        public Fixture Jw { get; set; }
        public Fixture Jx { get; set; }
        public Fixture Jy { get; set; }
        public Fixture Jz { get; set; }
        public Fixture Ka { get; set; }
        public Fixture Kb { get; set; }
        public Fixture Kc { get; set; }
        public Fixture Kd { get; set; }
        public Fixture Ke { get; set; }
        public Fixture Kf { get; set; }
        public Fixture Kg { get; set; }
        public Fixture Kh { get; set; }
        public Fixture Ki { get; set; }
        public Fixture Kj { get; set; }
        public Fixture Kk { get; set; }
        public Fixture Kl { get; set; }
        public Fixture Km { get; set; }
        public Fixture Kn { get; set; }
        public Fixture Ko { get; set; }
        public Fixture Kp { get; set; }
        public Fixture Kq { get; set; }
        public Fixture Kr { get; set; }
        public Fixture Ks { get; set; }
        public Fixture Kt { get; set; }
        public Fixture Ku { get; set; }
        public Fixture Kv { get; set; }
        public Fixture Kw { get; set; }
        public Fixture Kx { get; set; }
        public Fixture Ky { get; set; }
        public Fixture Kz { get; set; }
        public Fixture La { get; set; }
        public Fixture Lb { get; set; }
        public Fixture Lc { get; set; }
        public Fixture Ld { get; set; }
        public Fixture Le { get; set; }
        public Fixture Lf { get; set; }
        public Fixture Lg { get; set; }
        public Fixture Lh { get; set; }
        public Fixture Li { get; set; }
        public Fixture Lj { get; set; }
        public Fixture Lk { get; set; }
        public Fixture Ll { get; set; }
        public Fixture Lm { get; set; }
        public Fixture Ln { get; set; }
        public Fixture Lo { get; set; }
        public Fixture Lp { get; set; }
        public Fixture Lq { get; set; }
        public Fixture Lr { get; set; }
        public Fixture Ls { get; set; }
        public Fixture Lt { get; set; }
        public Fixture Lu { get; set; }
        public Fixture Lv { get; set; }
        public Fixture Lw { get; set; }
        public Fixture Lx { get; set; }
        public Fixture Ly { get; set; }
        public Fixture Lz { get; set; }
        public Fixture Ma { get; set; }
        public Fixture Mb { get; set; }
        public Fixture Mc { get; set; }
        public Fixture Md { get; set; }
        public Fixture Me { get; set; }
        public Fixture Mf { get; set; }
        public Fixture Mg { get; set; }
        public Fixture Mh { get; set; }
        public Fixture Mi { get; set; }
        public Fixture Mj { get; set; }
        public Fixture Mk { get; set; }
        public Fixture Ml { get; set; }
        public Fixture Mm { get; set; }
        public Fixture Mn { get; set; }
        public Fixture Mo { get; set; }
        public Fixture Mp { get; set; }
        public Fixture Mq { get; set; }
        public Fixture Mr { get; set; }
        public Fixture Ms { get; set; }
        public Fixture Mt { get; set; }
        public Fixture Mu { get; set; }
        public Fixture Mv { get; set; }
        public Fixture Mw { get; set; }
        public Fixture Mx { get; set; }
        public Fixture My { get; set; }
        public Fixture Mz { get; set; }
        public Fixture Na { get; set; }
        public Fixture Nb { get; set; }
        public Fixture Nc { get; set; }
        public Fixture Nd { get; set; }
        public Fixture Ne { get; set; }
        public Fixture Nf { get; set; }
        public Fixture Ng { get; set; }
        public Fixture Nh { get; set; }
        public Fixture Ni { get; set; }
        public Fixture Nj { get; set; }
        public Fixture Nk { get; set; }
        public Fixture Nl { get; set; }
        public Fixture Nm { get; set; }
        public Fixture Nn { get; set; }
        public Fixture No { get; set; }
        public Fixture Np { get; set; }
        public Fixture Nq { get; set; }
        public Fixture Nr { get; set; }
        public Fixture Ns { get; set; }
        public Fixture Nt { get; set; }
        public Fixture Nu { get; set; }
        public Fixture Nv { get; set; }
        public Fixture Nw { get; set; }
        public Fixture Nx { get; set; }
        public Fixture Ny { get; set; }
        public Fixture Nz { get; set; }
        public Fixture Oa { get; set; }
        public Fixture Ob { get; set; }
        public Fixture Oc { get; set; }
        public Fixture Od { get; set; }
        public Fixture Oe { get; set; }
        public Fixture Of { get; set; }
        public Fixture Og { get; set; }
        public Fixture Oh { get; set; }
        public Fixture Oi { get; set; }
        public Fixture Oj { get; set; }
        public Fixture Ok { get; set; }
        public Fixture Ol { get; set; }
        public Fixture Om { get; set; }
        public Fixture On { get; set; }
        public Fixture Oo { get; set; }
        public Fixture Op { get; set; }
        public Fixture Oq { get; set; }
        public Fixture Or { get; set; }
        public Fixture Os { get; set; }
        public Fixture Ot { get; set; }
        public Fixture Ou { get; set; }
        public Fixture Ov { get; set; }
        public Fixture Ow { get; set; }
        public Fixture Ox { get; set; }
        public Fixture Oy { get; set; }
        public Fixture Oz { get; set; }
        public Fixture Pa { get; set; }
        public Fixture Pb { get; set; }
        public Fixture Pc { get; set; }
        public Fixture Pd { get; set; }
        public Fixture Pe { get; set; }
        public Fixture Pf { get; set; }
        public Fixture Pg { get; set; }
        public Fixture Ph { get; set; }
        public Fixture Pi { get; set; }
        public Fixture Pj { get; set; }
        public Fixture Pk { get; set; }
        public Fixture Pl { get; set; }
        public Fixture Pm { get; set; }
        public Fixture Pn { get; set; }
        public Fixture Po { get; set; }
        public Fixture Pp { get; set; }
        public Fixture Pq { get; set; }
        public Fixture Pr { get; set; }
        public Fixture Ps { get; set; }
        public Fixture Pt { get; set; }
        public Fixture Pu { get; set; }
        public Fixture Pv { get; set; }
        public Fixture Pw { get; set; }
        public Fixture Px { get; set; }
        public Fixture Py { get; set; }
        public Fixture Pz { get; set; }
        public Fixture Qa { get; set; }
        public Fixture Qb { get; set; }
        public Fixture Qc { get; set; }
        public Fixture Qd { get; set; }
        public Fixture Qe { get; set; }
        public Fixture Qf { get; set; }
        public Fixture Qg { get; set; }
        public Fixture Qh { get; set; }
        public Fixture Qi { get; set; }
        public Fixture Qj { get; set; }
        public Fixture Qk { get; set; }
        public Fixture Ql { get; set; }
        public Fixture Qm { get; set; }
        public Fixture Qn { get; set; }
        public Fixture Qo { get; set; }
        public Fixture Qp { get; set; }
        public Fixture Qq { get; set; }
        public Fixture Qr { get; set; }
        public Fixture Qs { get; set; }
        public Fixture Qt { get; set; }
        public Fixture Qu { get; set; }
        public Fixture Qv { get; set; }
        public Fixture Qw { get; set; }
        public Fixture Qx { get; set; }
        public Fixture Qy { get; set; }
        public Fixture Qz { get; set; }
        public Fixture Ra { get; set; }
        public Fixture Rb { get; set; }
        public Fixture Rc { get; set; }
        public Fixture Rd { get; set; }
        public Fixture Re { get; set; }
        public Fixture Rf { get; set; }
        public Fixture Rg { get; set; }
        public Fixture Rh { get; set; }
        public Fixture Ri { get; set; }
        public Fixture Rj { get; set; }
        public Fixture Rk { get; set; }
        public Fixture Rl { get; set; }
        public Fixture Rm { get; set; }
        public Fixture Rn { get; set; }
        public Fixture Ro { get; set; }
        public Fixture Rp { get; set; }
        public Fixture Rq { get; set; }
        public Fixture Rr { get; set; }
        public Fixture Rs { get; set; }
        public Fixture Rt { get; set; }
        public Fixture Ru { get; set; }
        public Fixture Rv { get; set; }
        public Fixture Rw { get; set; }
        public Fixture Rx { get; set; }
        public Fixture Ry { get; set; }
        public Fixture Rz { get; set; }
        public Fixture Sa { get; set; }
        public Fixture Sb { get; set; }
        public Fixture Sc { get; set; }
        public Fixture Sd { get; set; }
        public Fixture Se { get; set; }
        public Fixture Sf { get; set; }
        public Fixture Sg { get; set; }
        public Fixture Sh { get; set; }
        public Fixture Si { get; set; }
        public Fixture Sj { get; set; }
        public Fixture Sk { get; set; }
        public Fixture Sl { get; set; }
        public Fixture Sm { get; set; }
        public Fixture Sn { get; set; }
        public Fixture So { get; set; }
        public Fixture Sp { get; set; }
        public Fixture Sq { get; set; }
        public Fixture Sr { get; set; }
        public Fixture Ss { get; set; }
        public Fixture St { get; set; }
        public Fixture Su { get; set; }
        public Fixture Sv { get; set; }
        public Fixture Sw { get; set; }
        public Fixture Sx { get; set; }
        public Fixture Sy { get; set; }
        public Fixture Sz { get; set; }
        public Fixture Ta { get; set; }
        public Fixture Tb { get; set; }
        public Fixture Tc { get; set; }
        public Fixture Td { get; set; }
        public Fixture Te { get; set; }
        public Fixture Tf { get; set; }
        public Fixture Tg { get; set; }
        public Fixture Th { get; set; }
        public Fixture Ti { get; set; }
        public Fixture Tj { get; set; }
        public Fixture Tk { get; set; }
        public Fixture Tl { get; set; }
        public Fixture Tm { get; set; }
        public Fixture Tn { get; set; }
        public Fixture To { get; set; }
        public Fixture Tp { get; set; }
        public Fixture Tq { get; set; }
        public Fixture Tr { get; set; }
        public Fixture Ts { get; set; }
        public Fixture Tt { get; set; }
        public Fixture Tu { get; set; }
        public Fixture Tv { get; set; }
        public Fixture Tw { get; set; }
        public Fixture Tx { get; set; }
        public Fixture Ty { get; set; }
        public Fixture Tz { get; set; }
        public Fixture Ua { get; set; }
        public Fixture Ub { get; set; }
        public Fixture Uc { get; set; }
        public Fixture Ud { get; set; }
        public Fixture Ue { get; set; }
        public Fixture Uf { get; set; }
        public Fixture Ug { get; set; }
        public Fixture Uh { get; set; }
        public Fixture Ui { get; set; }
        public Fixture Uj { get; set; }
        public Fixture Uk { get; set; }
        public Fixture Ul { get; set; }
        public Fixture Um { get; set; }
        public Fixture Un { get; set; }
        public Fixture Uo { get; set; }
        public Fixture Up { get; set; }
        public Fixture Uq { get; set; }
        public Fixture Ur { get; set; }
        public Fixture Us { get; set; }
        public Fixture Ut { get; set; }
        public Fixture Uu { get; set; }
        public Fixture Uv { get; set; }
        public Fixture Uw { get; set; }
        public Fixture Ux { get; set; }
        public Fixture Uy { get; set; }
        public Fixture Uz { get; set; }
        public Fixture Va { get; set; }
        public Fixture Vb { get; set; }
        public Fixture Vc { get; set; }
        public Fixture Vd { get; set; }
        public Fixture Ve { get; set; }
        public Fixture Vf { get; set; }
        public Fixture Vg { get; set; }
        public Fixture Vh { get; set; }
        public Fixture Vi { get; set; }
        public Fixture Vj { get; set; }
        public Fixture Vk { get; set; }
        public Fixture Vl { get; set; }
        public Fixture Vm { get; set; }
        public Fixture Vn { get; set; }
        public Fixture Vo { get; set; }
        public Fixture Vp { get; set; }
        public Fixture Vq { get; set; }
        public Fixture Vr { get; set; }
        public Fixture Vs { get; set; }
        public Fixture Vt { get; set; }
        public Fixture Vu { get; set; }
        public Fixture Vv { get; set; }
        public Fixture Vw { get; set; }
        public Fixture Vx { get; set; }
        public Fixture Vy { get; set; }
        public Fixture Vz { get; set; }
        public Fixture Wa { get; set; }
        public Fixture Wb { get; set; }
        public Fixture Wc { get; set; }
        public Fixture Wd { get; set; }
        public Fixture We { get; set; }
        public Fixture Wf { get; set; }
        public Fixture Wg { get; set; }
        public Fixture Wh { get; set; }
        public Fixture Wi { get; set; }
        public Fixture Wj { get; set; }
        public Fixture Wk { get; set; }
        public Fixture Wl { get; set; }
        public Fixture Wm { get; set; }
        public Fixture Wn { get; set; }
        public Fixture Wo { get; set; }
        public Fixture Wp { get; set; }
        public Fixture Wq { get; set; }
        public Fixture Wr { get; set; }
        public Fixture Ws { get; set; }
        public Fixture Wt { get; set; }
        public Fixture Wu { get; set; }
        public Fixture Wv { get; set; }
        public Fixture Ww { get; set; }
        public Fixture Wx { get; set; }
        public Fixture Wy { get; set; }
        public Fixture Wz { get; set; }
        public Fixture Xa { get; set; }
        public Fixture Xb { get; set; }
        public Fixture Xc { get; set; }
        public Fixture Xd { get; set; }
        public Fixture Xe { get; set; }
        public Fixture Xf { get; set; }
        public Fixture Xg { get; set; }
        public Fixture Xh { get; set; }
        public Fixture Xi { get; set; }
        public Fixture Xj { get; set; }
        public Fixture Xk { get; set; }
        public Fixture Xl { get; set; }
        public Fixture Xm { get; set; }
        public Fixture Xn { get; set; }
        public Fixture Xo { get; set; }
        public Fixture Xp { get; set; }
        public Fixture Xq { get; set; }
        public Fixture Xr { get; set; }
        public Fixture Xs { get; set; }
        public Fixture Xt { get; set; }
        public Fixture Xu { get; set; }
        public Fixture Xv { get; set; }
        public Fixture Xw { get; set; }
        public Fixture Xx { get; set; }
        public Fixture Xy { get; set; }
        public Fixture Xz { get; set; }
        public Fixture Ya { get; set; }
        public Fixture Yb { get; set; }
        public Fixture Yc { get; set; }
        public Fixture Yd { get; set; }
        public Fixture Ye { get; set; }
        public Fixture Yf { get; set; }
        public Fixture Yg { get; set; }
        public Fixture Yh { get; set; }
        public Fixture Yi { get; set; }
        public Fixture Yj { get; set; }
        public Fixture Yk { get; set; }
        public Fixture Yl { get; set; }
        public Fixture Ym { get; set; }
        public Fixture Yn { get; set; }
        public Fixture Yo { get; set; }
        public Fixture Yp { get; set; }
        public Fixture Yq { get; set; }
        public Fixture Yr { get; set; }
        public Fixture Ys { get; set; }
        public Fixture Yt { get; set; }
        public Fixture Yu { get; set; }
        public Fixture Yv { get; set; }
        public Fixture Yw { get; set; }
        public Fixture Yx { get; set; }
        public Fixture Yy { get; set; }
        public Fixture Yz { get; set; }
        public Fixture Za { get; set; }
        public Fixture Zb { get; set; }
        public Fixture Zc { get; set; }
        public Fixture Zd { get; set; }
        public Fixture Ze { get; set; }
        public Fixture Zf { get; set; }
        public Fixture Zg { get; set; }
        public Fixture Zh { get; set; }
        public Fixture Zi { get; set; }
        public Fixture Zj { get; set; }
        public Fixture Zk { get; set; }
        public Fixture Zl { get; set; }
        public Fixture Zm { get; set; }
        public Fixture Zn { get; set; }
        public Fixture Zo { get; set; }
        public Fixture Zp { get; set; }
        public Fixture Zq { get; set; }
        public Fixture Zr { get; set; }
        public Fixture Zs { get; set; }
        public Fixture Zt { get; set; }
        public Fixture Zu { get; set; }
        public Fixture Zv { get; set; }
        public Fixture Zw { get; set; }
        public Fixture Zx { get; set; }
        public Fixture Zy { get; set; }
        public Fixture Zz { get; set; }
    }
}
