namespace GhostsAreRealButTheirIntelligenceIsArtificial.Core.Objects
{
    public class Maze
    {
        public string Aa { get; set; }
        public string Ab { get; set; }
        public string Ac { get; set; }
        public string Ad { get; set; }
        public string Ae { get; set; }
        public string Af { get; set; }
        public string Ag { get; set; }
        public string Ah { get; set; }
        public string Ai { get; set; }
        public string Aj { get; set; }
        public string Ak { get; set; }
        public string Al { get; set; }
        public string Am { get; set; }
        public string An { get; set; }
        public string Ao { get; set; }
        public string Ap { get; set; }
        public string Aq { get; set; }
        public string Ar { get; set; }
        public string As { get; set; }
        public string At { get; set; }
        public string Au { get; set; }
        public string Av { get; set; }
        public string Aw { get; set; }
        public string Ax { get; set; }
        public string Ay { get; set; }
        public string Az { get; set; }
        public string Ba { get; set; }
        public string Bb { get; set; }
        public string Bc { get; set; }
        public string Bd { get; set; }
        public string Be { get; set; }
        public string Bf { get; set; }
        public string Bg { get; set; }
        public string Bh { get; set; }
        public string Bi { get; set; }
        public string Bj { get; set; }
        public string Bk { get; set; }
        public string Bl { get; set; }
        public string Bm { get; set; }
        public string Bn { get; set; }
        public string Bo { get; set; }
        public string Bp { get; set; }
        public string Bq { get; set; }
        public string Br { get; set; }
        public string Bs { get; set; }
        public string Bt { get; set; }
        public string Bu { get; set; }
        public string Bv { get; set; }
        public string Bw { get; set; }
        public string Bx { get; set; }
        public string By { get; set; }
        public string Bz { get; set; }
        public string Ca { get; set; }
        public string Cb { get; set; }
        public string Cc { get; set; }
        public string Cd { get; set; }
        public string Ce { get; set; }
        public string Cf { get; set; }
        public string Cg { get; set; }
        public string Ch { get; set; }
        public string Ci { get; set; }
        public string Cj { get; set; }
        public string Ck { get; set; }
        public string Cl { get; set; }
        public string Cm { get; set; }
        public string Cn { get; set; }
        public string Co { get; set; }
        public string Cp { get; set; }
        public string Cq { get; set; }
        public string Cr { get; set; }
        public string Cs { get; set; }
        public string Ct { get; set; }
        public string Cu { get; set; }
        public string Cv { get; set; }
        public string Cw { get; set; }
        public string Cx { get; set; }
        public string Cy { get; set; }
        public string Cz { get; set; }
        public string Da { get; set; }
        public string Db { get; set; }
        public string Dc { get; set; }
        public string Dd { get; set; }
        public string De { get; set; }
        public string Df { get; set; }
        public string Dg { get; set; }
        public string Dh { get; set; }
        public string Di { get; set; }
        public string Dj { get; set; }
        public string Dk { get; set; }
        public string Dl { get; set; }
        public string Dm { get; set; }
        public string Dn { get; set; }
        public string Do { get; set; }
        public string Dp { get; set; }
        public string Dq { get; set; }
        public string Dr { get; set; }
        public string Ds { get; set; }
        public string Dt { get; set; }
        public string Du { get; set; }
        public string Dv { get; set; }
        public string Dw { get; set; }
        public string Dx { get; set; }
        public string Dy { get; set; }
        public string Dz { get; set; }
        public string Ea { get; set; }
        public string Eb { get; set; }
        public string Ec { get; set; }
        public string Ed { get; set; }
        public string Ee { get; set; }
        public string Ef { get; set; }
        public string Eg { get; set; }
        public string Eh { get; set; }
        public string Ei { get; set; }
        public string Ej { get; set; }
        public string Ek { get; set; }
        public string El { get; set; }
        public string Em { get; set; }
        public string En { get; set; }
        public string Eo { get; set; }
        public string Ep { get; set; }
        public string Eq { get; set; }
        public string Er { get; set; }
        public string Es { get; set; }
        public string Et { get; set; }
        public string Eu { get; set; }
        public string Ev { get; set; }
        public string Ew { get; set; }
        public string Ex { get; set; }
        public string Ey { get; set; }
        public string Ez { get; set; }
        public string Fa { get; set; }
        public string Fb { get; set; }
        public string Fc { get; set; }
        public string Fd { get; set; }
        public string Fe { get; set; }
        public string Ff { get; set; }
        public string Fg { get; set; }
        public string Fh { get; set; }
        public string Fi { get; set; }
        public string Fj { get; set; }
        public string Fk { get; set; }
        public string Fl { get; set; }
        public string Fm { get; set; }
        public string Fn { get; set; }
        public string Fo { get; set; }
        public string Fp { get; set; }
        public string Fq { get; set; }
        public string Fr { get; set; }
        public string Fs { get; set; }
        public string Ft { get; set; }
        public string Fu { get; set; }
        public string Fv { get; set; }
        public string Fw { get; set; }
        public string Fx { get; set; }
        public string Fy { get; set; }
        public string Fz { get; set; }
        public string Ga { get; set; }
        public string Gb { get; set; }
        public string Gc { get; set; }
        public string Gd { get; set; }
        public string Ge { get; set; }
        public string Gf { get; set; }
        public string Gg { get; set; }
        public string Gh { get; set; }
        public string Gi { get; set; }
        public string Gj { get; set; }
        public string Gk { get; set; }
        public string Gl { get; set; }
        public string Gm { get; set; }
        public string Gn { get; set; }
        public string Go { get; set; }
        public string Gp { get; set; }
        public string Gq { get; set; }
        public string Gr { get; set; }
        public string Gs { get; set; }
        public string Gt { get; set; }
        public string Gu { get; set; }
        public string Gv { get; set; }
        public string Gw { get; set; }
        public string Gx { get; set; }
        public string Gy { get; set; }
        public string Gz { get; set; }
        public string Ha { get; set; }
        public string Hb { get; set; }
        public string Hc { get; set; }
        public string Hd { get; set; }
        public string He { get; set; }
        public string Hf { get; set; }
        public string Hg { get; set; }
        public string Hh { get; set; }
        public string Hi { get; set; }
        public string Hj { get; set; }
        public string Hk { get; set; }
        public string Hl { get; set; }
        public string Hm { get; set; }
        public string Hn { get; set; }
        public string Ho { get; set; }
        public string Hp { get; set; }
        public string Hq { get; set; }
        public string Hr { get; set; }
        public string Hs { get; set; }
        public string Ht { get; set; }
        public string Hu { get; set; }
        public string Hv { get; set; }
        public string Hw { get; set; }
        public string Hx { get; set; }
        public string Hy { get; set; }
        public string Hz { get; set; }
        public string Ia { get; set; }
        public string Ib { get; set; }
        public string Ic { get; set; }
        public string Id { get; set; }
        public string Ie { get; set; }
        public string If { get; set; }
        public string Ig { get; set; }
        public string Ih { get; set; }
        public string Ii { get; set; }
        public string Ij { get; set; }
        public string Ik { get; set; }
        public string Il { get; set; }
        public string Im { get; set; }
        public string In { get; set; }
        public string Io { get; set; }
        public string Ip { get; set; }
        public string Iq { get; set; }
        public string Ir { get; set; }
        public string Is { get; set; }
        public string It { get; set; }
        public string Iu { get; set; }
        public string Iv { get; set; }
        public string Iw { get; set; }
        public string Ix { get; set; }
        public string Iy { get; set; }
        public string Iz { get; set; }
        public string Ja { get; set; }
        public string Jb { get; set; }
        public string Jc { get; set; }
        public string Jd { get; set; }
        public string Je { get; set; }
        public string Jf { get; set; }
        public string Jg { get; set; }
        public string Jh { get; set; }
        public string Ji { get; set; }
        public string Jj { get; set; }
        public string Jk { get; set; }
        public string Jl { get; set; }
        public string Jm { get; set; }
        public string Jn { get; set; }
        public string Jo { get; set; }
        public string Jp { get; set; }
        public string Jq { get; set; }
        public string Jr { get; set; }
        public string Js { get; set; }
        public string Jt { get; set; }
        public string Ju { get; set; }
        public string Jv { get; set; }
        public string Jw { get; set; }
        public string Jx { get; set; }
        public string Jy { get; set; }
        public string Jz { get; set; }
        public string Ka { get; set; }
        public string Kb { get; set; }
        public string Kc { get; set; }
        public string Kd { get; set; }
        public string Ke { get; set; }
        public string Kf { get; set; }
        public string Kg { get; set; }
        public string Kh { get; set; }
        public string Ki { get; set; }
        public string Kj { get; set; }
        public string Kk { get; set; }
        public string Kl { get; set; }
        public string Km { get; set; }
        public string Kn { get; set; }
        public string Ko { get; set; }
        public string Kp { get; set; }
        public string Kq { get; set; }
        public string Kr { get; set; }
        public string Ks { get; set; }
        public string Kt { get; set; }
        public string Ku { get; set; }
        public string Kv { get; set; }
        public string Kw { get; set; }
        public string Kx { get; set; }
        public string Ky { get; set; }
        public string Kz { get; set; }
        public string La { get; set; }
        public string Lb { get; set; }
        public string Lc { get; set; }
        public string Ld { get; set; }
        public string Le { get; set; }
        public string Lf { get; set; }
        public string Lg { get; set; }
        public string Lh { get; set; }
        public string Li { get; set; }
        public string Lj { get; set; }
        public string Lk { get; set; }
        public string Ll { get; set; }
        public string Lm { get; set; }
        public string Ln { get; set; }
        public string Lo { get; set; }
        public string Lp { get; set; }
        public string Lq { get; set; }
        public string Lr { get; set; }
        public string Ls { get; set; }
        public string Lt { get; set; }
        public string Lu { get; set; }
        public string Lv { get; set; }
        public string Lw { get; set; }
        public string Lx { get; set; }
        public string Ly { get; set; }
        public string Lz { get; set; }
        public string Ma { get; set; }
        public string Mb { get; set; }
        public string Mc { get; set; }
        public string Md { get; set; }
        public string Me { get; set; }
        public string Mf { get; set; }
        public string Mg { get; set; }
        public string Mh { get; set; }
        public string Mi { get; set; }
        public string Mj { get; set; }
        public string Mk { get; set; }
        public string Ml { get; set; }
        public string Mm { get; set; }
        public string Mn { get; set; }
        public string Mo { get; set; }
        public string Mp { get; set; }
        public string Mq { get; set; }
        public string Mr { get; set; }
        public string Ms { get; set; }
        public string Mt { get; set; }
        public string Mu { get; set; }
        public string Mv { get; set; }
        public string Mw { get; set; }
        public string Mx { get; set; }
        public string My { get; set; }
        public string Mz { get; set; }
        public string Na { get; set; }
        public string Nb { get; set; }
        public string Nc { get; set; }
        public string Nd { get; set; }
        public string Ne { get; set; }
        public string Nf { get; set; }
        public string Ng { get; set; }
        public string Nh { get; set; }
        public string Ni { get; set; }
        public string Nj { get; set; }
        public string Nk { get; set; }
        public string Nl { get; set; }
        public string Nm { get; set; }
        public string Nn { get; set; }
        public string No { get; set; }
        public string Np { get; set; }
        public string Nq { get; set; }
        public string Nr { get; set; }
        public string Ns { get; set; }
        public string Nt { get; set; }
        public string Nu { get; set; }
        public string Nv { get; set; }
        public string Nw { get; set; }
        public string Nx { get; set; }
        public string Ny { get; set; }
        public string Nz { get; set; }
        public string Oa { get; set; }
        public string Ob { get; set; }
        public string Oc { get; set; }
        public string Od { get; set; }
        public string Oe { get; set; }
        public string Of { get; set; }
        public string Og { get; set; }
        public string Oh { get; set; }
        public string Oi { get; set; }
        public string Oj { get; set; }
        public string Ok { get; set; }
        public string Ol { get; set; }
        public string Om { get; set; }
        public string On { get; set; }
        public string Oo { get; set; }
        public string Op { get; set; }
        public string Oq { get; set; }
        public string Or { get; set; }
        public string Os { get; set; }
        public string Ot { get; set; }
        public string Ou { get; set; }
        public string Ov { get; set; }
        public string Ow { get; set; }
        public string Ox { get; set; }
        public string Oy { get; set; }
        public string Oz { get; set; }
        public string Pa { get; set; }
        public string Pb { get; set; }
        public string Pc { get; set; }
        public string Pd { get; set; }
        public string Pe { get; set; }
        public string Pf { get; set; }
        public string Pg { get; set; }
        public string Ph { get; set; }
        public string Pi { get; set; }
        public string Pj { get; set; }
        public string Pk { get; set; }
        public string Pl { get; set; }
        public string Pm { get; set; }
        public string Pn { get; set; }
        public string Po { get; set; }
        public string Pp { get; set; }
        public string Pq { get; set; }
        public string Pr { get; set; }
        public string Ps { get; set; }
        public string Pt { get; set; }
        public string Pu { get; set; }
        public string Pv { get; set; }
        public string Pw { get; set; }
        public string Px { get; set; }
        public string Py { get; set; }
        public string Pz { get; set; }
        public string Qa { get; set; }
        public string Qb { get; set; }
        public string Qc { get; set; }
        public string Qd { get; set; }
        public string Qe { get; set; }
        public string Qf { get; set; }
        public string Qg { get; set; }
        public string Qh { get; set; }
        public string Qi { get; set; }
        public string Qj { get; set; }
        public string Qk { get; set; }
        public string Ql { get; set; }
        public string Qm { get; set; }
        public string Qn { get; set; }
        public string Qo { get; set; }
        public string Qp { get; set; }
        public string Qq { get; set; }
        public string Qr { get; set; }
        public string Qs { get; set; }
        public string Qt { get; set; }
        public string Qu { get; set; }
        public string Qv { get; set; }
        public string Qw { get; set; }
        public string Qx { get; set; }
        public string Qy { get; set; }
        public string Qz { get; set; }
        public string Ra { get; set; }
        public string Rb { get; set; }
        public string Rc { get; set; }
        public string Rd { get; set; }
        public string Re { get; set; }
        public string Rf { get; set; }
        public string Rg { get; set; }
        public string Rh { get; set; }
        public string Ri { get; set; }
        public string Rj { get; set; }
        public string Rk { get; set; }
        public string Rl { get; set; }
        public string Rm { get; set; }
        public string Rn { get; set; }
        public string Ro { get; set; }
        public string Rp { get; set; }
        public string Rq { get; set; }
        public string Rr { get; set; }
        public string Rs { get; set; }
        public string Rt { get; set; }
        public string Ru { get; set; }
        public string Rv { get; set; }
        public string Rw { get; set; }
        public string Rx { get; set; }
        public string Ry { get; set; }
        public string Rz { get; set; }
        public string Sa { get; set; }
        public string Sb { get; set; }
        public string Sc { get; set; }
        public string Sd { get; set; }
        public string Se { get; set; }
        public string Sf { get; set; }
        public string Sg { get; set; }
        public string Sh { get; set; }
        public string Si { get; set; }
        public string Sj { get; set; }
        public string Sk { get; set; }
        public string Sl { get; set; }
        public string Sm { get; set; }
        public string Sn { get; set; }
        public string So { get; set; }
        public string Sp { get; set; }
        public string Sq { get; set; }
        public string Sr { get; set; }
        public string Ss { get; set; }
        public string St { get; set; }
        public string Su { get; set; }
        public string Sv { get; set; }
        public string Sw { get; set; }
        public string Sx { get; set; }
        public string Sy { get; set; }
        public string Sz { get; set; }
        public string Ta { get; set; }
        public string Tb { get; set; }
        public string Tc { get; set; }
        public string Td { get; set; }
        public string Te { get; set; }
        public string Tf { get; set; }
        public string Tg { get; set; }
        public string Th { get; set; }
        public string Ti { get; set; }
        public string Tj { get; set; }
        public string Tk { get; set; }
        public string Tl { get; set; }
        public string Tm { get; set; }
        public string Tn { get; set; }
        public string To { get; set; }
        public string Tp { get; set; }
        public string Tq { get; set; }
        public string Tr { get; set; }
        public string Ts { get; set; }
        public string Tt { get; set; }
        public string Tu { get; set; }
        public string Tv { get; set; }
        public string Tw { get; set; }
        public string Tx { get; set; }
        public string Ty { get; set; }
        public string Tz { get; set; }
        public string Ua { get; set; }
        public string Ub { get; set; }
        public string Uc { get; set; }
        public string Ud { get; set; }
        public string Ue { get; set; }
        public string Uf { get; set; }
        public string Ug { get; set; }
        public string Uh { get; set; }
        public string Ui { get; set; }
        public string Uj { get; set; }
        public string Uk { get; set; }
        public string Ul { get; set; }
        public string Um { get; set; }
        public string Un { get; set; }
        public string Uo { get; set; }
        public string Up { get; set; }
        public string Uq { get; set; }
        public string Ur { get; set; }
        public string Us { get; set; }
        public string Ut { get; set; }
        public string Uu { get; set; }
        public string Uv { get; set; }
        public string Uw { get; set; }
        public string Ux { get; set; }
        public string Uy { get; set; }
        public string Uz { get; set; }
        public string Va { get; set; }
        public string Vb { get; set; }
        public string Vc { get; set; }
        public string Vd { get; set; }
        public string Ve { get; set; }
        public string Vf { get; set; }
        public string Vg { get; set; }
        public string Vh { get; set; }
        public string Vi { get; set; }
        public string Vj { get; set; }
        public string Vk { get; set; }
        public string Vl { get; set; }
        public string Vm { get; set; }
        public string Vn { get; set; }
        public string Vo { get; set; }
        public string Vp { get; set; }
        public string Vq { get; set; }
        public string Vr { get; set; }
        public string Vs { get; set; }
        public string Vt { get; set; }
        public string Vu { get; set; }
        public string Vv { get; set; }
        public string Vw { get; set; }
        public string Vx { get; set; }
        public string Vy { get; set; }
        public string Vz { get; set; }
        public string Wa { get; set; }
        public string Wb { get; set; }
        public string Wc { get; set; }
        public string Wd { get; set; }
        public string We { get; set; }
        public string Wf { get; set; }
        public string Wg { get; set; }
        public string Wh { get; set; }
        public string Wi { get; set; }
        public string Wj { get; set; }
        public string Wk { get; set; }
        public string Wl { get; set; }
        public string Wm { get; set; }
        public string Wn { get; set; }
        public string Wo { get; set; }
        public string Wp { get; set; }
        public string Wq { get; set; }
        public string Wr { get; set; }
        public string Ws { get; set; }
        public string Wt { get; set; }
        public string Wu { get; set; }
        public string Wv { get; set; }
        public string Ww { get; set; }
        public string Wx { get; set; }
        public string Wy { get; set; }
        public string Wz { get; set; }
        public string Xa { get; set; }
        public string Xb { get; set; }
        public string Xc { get; set; }
        public string Xd { get; set; }
        public string Xe { get; set; }
        public string Xf { get; set; }
        public string Xg { get; set; }
        public string Xh { get; set; }
        public string Xi { get; set; }
        public string Xj { get; set; }
        public string Xk { get; set; }
        public string Xl { get; set; }
        public string Xm { get; set; }
        public string Xn { get; set; }
        public string Xo { get; set; }
        public string Xp { get; set; }
        public string Xq { get; set; }
        public string Xr { get; set; }
        public string Xs { get; set; }
        public string Xt { get; set; }
        public string Xu { get; set; }
        public string Xv { get; set; }
        public string Xw { get; set; }
        public string Xx { get; set; }
        public string Xy { get; set; }
        public string Xz { get; set; }
        public string Ya { get; set; }
        public string Yb { get; set; }
        public string Yc { get; set; }
        public string Yd { get; set; }
        public string Ye { get; set; }
        public string Yf { get; set; }
        public string Yg { get; set; }
        public string Yh { get; set; }
        public string Yi { get; set; }
        public string Yj { get; set; }
        public string Yk { get; set; }
        public string Yl { get; set; }
        public string Ym { get; set; }
        public string Yn { get; set; }
        public string Yo { get; set; }
        public string Yp { get; set; }
        public string Yq { get; set; }
        public string Yr { get; set; }
        public string Ys { get; set; }
        public string Yt { get; set; }
        public string Yu { get; set; }
        public string Yv { get; set; }
        public string Yw { get; set; }
        public string Yx { get; set; }
        public string Yy { get; set; }
        public string Yz { get; set; }
        public string Za { get; set; }
        public string Zb { get; set; }
        public string Zc { get; set; }
        public string Zd { get; set; }
        public string Ze { get; set; }
        public string Zf { get; set; }
        public string Zg { get; set; }
        public string Zh { get; set; }
        public string Zi { get; set; }
        public string Zj { get; set; }
        public string Zk { get; set; }
        public string Zl { get; set; }
        public string Zm { get; set; }
        public string Zn { get; set; }
        public string Zo { get; set; }
        public string Zp { get; set; }
        public string Zq { get; set; }
        public string Zr { get; set; }
        public string Zs { get; set; }
        public string Zt { get; set; }
        public string Zu { get; set; }
        public string Zv { get; set; }
        public string Zw { get; set; }
        public string Zx { get; set; }
        public string Zy { get; set; }
        public string Zz { get; set; }
    }
}
